export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const AUTH_SIGNUP_ERROR = 'AUTH_SIGNUP_ERROR';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';

export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';
export const GET_NEWS_SUCCESS= 'GET_NEWS_SUCCESS';